// Code generated by protoc-gen-gogo.
// source: srv.proto
// DO NOT EDIT!

/*
Package testservice is a generated protocol buffer package.

It is generated from these files:
	srv.proto

It has these top-level messages:
	ReqSet
	RespSet
	ReqWait
	Info
	Empty
*/
package testservice

import proto "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

type ReqSet struct {
	Str string `protobuf:"bytes,1,opt,name=str,proto3" json:"str,omitempty"`
	Num uint64 `protobuf:"varint,2,opt,name=num,proto3" json:"num,omitempty"`
}

func (m *ReqSet) Reset()                    { *m = ReqSet{} }
func (m *ReqSet) String() string            { return proto.CompactTextString(m) }
func (*ReqSet) ProtoMessage()               {}
func (*ReqSet) Descriptor() ([]byte, []int) { return fileDescriptorSrv, []int{0} }

func (m *ReqSet) GetStr() string {
	if m != nil {
		return m.Str
	}
	return ""
}

func (m *ReqSet) GetNum() uint64 {
	if m != nil {
		return m.Num
	}
	return 0
}

type RespSet struct {
	Info  *Info  `protobuf:"bytes,1,opt,name=info" json:"info,omitempty"`
	Upper string `protobuf:"bytes,2,opt,name=upper,proto3" json:"upper,omitempty"`
	Mod7  uint64 `protobuf:"varint,3,opt,name=mod7,proto3" json:"mod7,omitempty"`
}

func (m *RespSet) Reset()                    { *m = RespSet{} }
func (m *RespSet) String() string            { return proto.CompactTextString(m) }
func (*RespSet) ProtoMessage()               {}
func (*RespSet) Descriptor() ([]byte, []int) { return fileDescriptorSrv, []int{1} }

func (m *RespSet) GetInfo() *Info {
	if m != nil {
		return m.Info
	}
	return nil
}

func (m *RespSet) GetUpper() string {
	if m != nil {
		return m.Upper
	}
	return ""
}

func (m *RespSet) GetMod7() uint64 {
	if m != nil {
		return m.Mod7
	}
	return 0
}

type ReqWait struct {
	Duration int64 `protobuf:"varint,1,opt,name=duration,proto3" json:"duration,omitempty"`
}

func (m *ReqWait) Reset()                    { *m = ReqWait{} }
func (m *ReqWait) String() string            { return proto.CompactTextString(m) }
func (*ReqWait) ProtoMessage()               {}
func (*ReqWait) Descriptor() ([]byte, []int) { return fileDescriptorSrv, []int{2} }

func (m *ReqWait) GetDuration() int64 {
	if m != nil {
		return m.Duration
	}
	return 0
}

type Info struct {
	Code        int32  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Error       string `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	TotalTimeNs int64  `protobuf:"varint,3,opt,name=total_time_ns,json=totalTimeNs,proto3" json:"total_time_ns,omitempty"`
}

func (m *Info) Reset()                    { *m = Info{} }
func (m *Info) String() string            { return proto.CompactTextString(m) }
func (*Info) ProtoMessage()               {}
func (*Info) Descriptor() ([]byte, []int) { return fileDescriptorSrv, []int{3} }

func (m *Info) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *Info) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (m *Info) GetTotalTimeNs() int64 {
	if m != nil {
		return m.TotalTimeNs
	}
	return 0
}

type Empty struct {
}

func (m *Empty) Reset()                    { *m = Empty{} }
func (m *Empty) String() string            { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()               {}
func (*Empty) Descriptor() ([]byte, []int) { return fileDescriptorSrv, []int{4} }

func init() {
	proto.RegisterType((*ReqSet)(nil), "testservice.ReqSet")
	proto.RegisterType((*RespSet)(nil), "testservice.RespSet")
	proto.RegisterType((*ReqWait)(nil), "testservice.ReqWait")
	proto.RegisterType((*Info)(nil), "testservice.Info")
	proto.RegisterType((*Empty)(nil), "testservice.Empty")
}

func init() { proto.RegisterFile("srv.proto", fileDescriptorSrv) }

var fileDescriptorSrv = []byte{
	// 280 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x91, 0x41, 0x4b, 0xc3, 0x40,
	0x10, 0x85, 0xa9, 0x49, 0x5a, 0x33, 0x41, 0xd0, 0xb5, 0x87, 0x90, 0x53, 0x59, 0x28, 0xf4, 0x20,
	0x41, 0xea, 0xc1, 0x93, 0x47, 0x0f, 0x5e, 0x3c, 0x6c, 0x0a, 0x82, 0x97, 0x12, 0x9b, 0x29, 0x2c,
	0x98, 0x6c, 0xba, 0x3b, 0x09, 0xf8, 0xef, 0x65, 0xa6, 0x52, 0x6c, 0x6f, 0x6f, 0xde, 0xce, 0x7e,
	0x8f, 0xb7, 0x0b, 0x69, 0xf0, 0x63, 0xd9, 0x7b, 0x47, 0x4e, 0x65, 0x84, 0x81, 0x02, 0xfa, 0xd1,
	0xee, 0x50, 0x3f, 0xc0, 0xd4, 0xe0, 0xa1, 0x42, 0x52, 0xb7, 0x10, 0x05, 0xf2, 0xf9, 0x64, 0x31,
	0x59, 0xa5, 0x86, 0x25, 0x3b, 0xdd, 0xd0, 0xe6, 0x57, 0x8b, 0xc9, 0x2a, 0x36, 0x2c, 0xf5, 0x27,
	0xcc, 0x0c, 0x86, 0x9e, 0xd7, 0x97, 0x10, 0xdb, 0x6e, 0xef, 0x64, 0x3f, 0x5b, 0xdf, 0x95, 0xff,
	0xa0, 0xe5, 0x5b, 0xb7, 0x77, 0x46, 0x8e, 0xd5, 0x1c, 0x92, 0xa1, 0xef, 0xd1, 0x0b, 0x25, 0x35,
	0xc7, 0x41, 0x29, 0x88, 0x5b, 0xd7, 0x3c, 0xe7, 0x91, 0xa0, 0x45, 0xeb, 0x25, 0xb3, 0x0f, 0x1f,
	0xb5, 0x25, 0x55, 0xc0, 0x75, 0x33, 0xf8, 0x9a, 0xac, 0xeb, 0x84, 0x1f, 0x99, 0xd3, 0xac, 0x37,
	0x10, 0x33, 0x9e, 0x11, 0x3b, 0xd7, 0xa0, 0x9c, 0x27, 0x46, 0x34, 0x87, 0xa1, 0xf7, 0xee, 0x14,
	0x26, 0x83, 0xd2, 0x70, 0x43, 0x8e, 0xea, 0xef, 0x2d, 0xd9, 0x16, 0xb7, 0x5d, 0x90, 0xd4, 0xc8,
	0x64, 0x62, 0x6e, 0x6c, 0x8b, 0xef, 0x41, 0xcf, 0x20, 0x79, 0x6d, 0x7b, 0xfa, 0x59, 0xbf, 0x40,
	0x5a, 0xf9, 0xb1, 0x42, 0x22, 0xf4, 0xea, 0x11, 0x22, 0xae, 0x7a, 0x7f, 0x56, 0xee, 0xf8, 0x5c,
	0xc5, 0xfc, 0xc2, 0x94, 0x57, 0xf9, 0xbb, 0xce, 0x25, 0xe4, 0x7a, 0x2c, 0x75, 0x2e, 0x57, 0xa5,
	0x64, 0xa1, 0xce, 0x5c, 0x49, 0xff, 0x9a, 0xca, 0x0f, 0x3d, 0xfd, 0x06, 0x00, 0x00, 0xff, 0xff,
	0x67, 0x8e, 0x26, 0x87, 0xae, 0x01, 0x00, 0x00,
}
