// Code generated by protoc-gen-gogo.
// source: api.proto
// DO NOT EDIT!

/*
Package api_v1 is a generated protocol buffer package.

It is generated from these files:
	api.proto

It has these top-level messages:
	ActualState
	ErrorResponse
	TransferOK
	Batch
	TransferRequest
	TransferResponse
	Limit
	Setting
	AccountSettingsRequest
	AccountSettingsResponse
	UpdateSettingsRequest
	UpdateSettingsResponse
	UpdateSettingsOK
	PrevHashRequest
	PrevHashResponse
	HistoryRequest
	HistoryResponse
	Txn
	StatsRequest
	StatsResponse
	AccountsRequest
	AccountsResponse
*/
package api_v1

import proto "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/gogo/protobuf/gogoproto"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

type ErrorResponse_ErrorType int32

const (
	ErrorResponse_GENERAL ErrorResponse_ErrorType = 0
	ErrorResponse_BALANCE ErrorResponse_ErrorType = 1
	ErrorResponse_POLICY  ErrorResponse_ErrorType = 2
)

var ErrorResponse_ErrorType_name = map[int32]string{
	0: "GENERAL",
	1: "BALANCE",
	2: "POLICY",
}
var ErrorResponse_ErrorType_value = map[string]int32{
	"GENERAL": 0,
	"BALANCE": 1,
	"POLICY":  2,
}

func (x ErrorResponse_ErrorType) String() string {
	return proto.EnumName(ErrorResponse_ErrorType_name, int32(x))
}
func (ErrorResponse_ErrorType) EnumDescriptor() ([]byte, []int) { return fileDescriptorApi, []int{1, 0} }

type HistoryRequest_Direction int32

const (
	HistoryRequest_BOTH   HistoryRequest_Direction = 0
	HistoryRequest_OUTPUT HistoryRequest_Direction = 1
	HistoryRequest_INPUT  HistoryRequest_Direction = 2
)

var HistoryRequest_Direction_name = map[int32]string{
	0: "BOTH",
	1: "OUTPUT",
	2: "INPUT",
}
var HistoryRequest_Direction_value = map[string]int32{
	"BOTH":   0,
	"OUTPUT": 1,
	"INPUT":  2,
}

func (x HistoryRequest_Direction) String() string {
	return proto.EnumName(HistoryRequest_Direction_name, int32(x))
}
func (HistoryRequest_Direction) EnumDescriptor() ([]byte, []int) {
	return fileDescriptorApi, []int{15, 0}
}

type ActualState struct {
	Account      Account `protobuf:"varint,1,opt,name=account,proto3,customtype=Account" json:"account"`
	Balance      int64   `protobuf:"varint,2,opt,name=balance,proto3" json:"balance,omitempty"`
	LastHash     Hash    `protobuf:"bytes,3,opt,name=last_hash,json=lastHash,proto3,customtype=Hash" json:"last_hash"`
	LastOpTimeNs int64   `protobuf:"varint,4,opt,name=last_op_time_ns,json=lastOpTimeNs,proto3" json:"last_op_time_ns,omitempty"`
	TraceId      string  `protobuf:"bytes,5,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
}

func (m *ActualState) Reset()                    { *m = ActualState{} }
func (m *ActualState) String() string            { return proto.CompactTextString(m) }
func (*ActualState) ProtoMessage()               {}
func (*ActualState) Descriptor() ([]byte, []int) { return fileDescriptorApi, []int{0} }

func (m *ActualState) GetBalance() int64 {
	if m != nil {
		return m.Balance
	}
	return 0
}

func (m *ActualState) GetLastOpTimeNs() int64 {
	if m != nil {
		return m.LastOpTimeNs
	}
	return 0
}

func (m *ActualState) GetTraceId() string {
	if m != nil {
		return m.TraceId
	}
	return ""
}

type ErrorResponse struct {
	Error     string                  `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	ErrorType ErrorResponse_ErrorType `protobuf:"varint,2,opt,name=error_type,json=errorType,proto3,enum=api_v1.ErrorResponse_ErrorType" json:"error_type,omitempty"`
}

func (m *ErrorResponse) Reset()                    { *m = ErrorResponse{} }
func (m *ErrorResponse) String() string            { return proto.CompactTextString(m) }
func (*ErrorResponse) ProtoMessage()               {}
func (*ErrorResponse) Descriptor() ([]byte, []int) { return fileDescriptorApi, []int{1} }

func (m *ErrorResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (m *ErrorResponse) GetErrorType() ErrorResponse_ErrorType {
	if m != nil {
		return m.ErrorType
	}
	return ErrorResponse_GENERAL
}

type TransferOK struct {
	SettingsId  int64 `protobuf:"varint,1,opt,name=settings_id,json=settingsId,proto3" json:"settings_id,omitempty"`
	LastBatchId int64 `protobuf:"varint,2,opt,name=last_batch_id,json=lastBatchId,proto3" json:"last_batch_id,omitempty"`
}

func (m *TransferOK) Reset()                    { *m = TransferOK{} }
func (m *TransferOK) String() string            { return proto.CompactTextString(m) }
func (*TransferOK) ProtoMessage()               {}
func (*TransferOK) Descriptor() ([]byte, []int) { return fileDescriptorApi, []int{2} }

func (m *TransferOK) GetSettingsId() int64 {
	if m != nil {
		return m.SettingsId
	}
	return 0
}

func (m *TransferOK) GetLastBatchId() int64 {
	if m != nil {
		return m.LastBatchId
	}
	return 0
}

type Batch struct {
	Receiver Account `protobuf:"varint,1,opt,name=receiver,proto3,customtype=Account" json:"receiver"`
	Amount   int64   `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"`
}

func (m *Batch) Reset()                    { *m = Batch{} }
func (m *Batch) String() string            { return proto.CompactTextString(m) }
func (*Batch) ProtoMessage()               {}
func (*Batch) Descriptor() ([]byte, []int) { return fileDescriptorApi, []int{3} }

func (m *Batch) GetAmount() int64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

type TransferRequest struct {
	Sender     Account  `protobuf:"varint,1,opt,name=sender,proto3,customtype=Account" json:"sender"`
	CreatedAt  int64    `protobuf:"varint,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	PrevHash   Hash     `protobuf:"bytes,3,opt,name=prev_hash,json=prevHash,proto3,customtype=Hash" json:"prev_hash"`
	SettingsId int64    `protobuf:"varint,4,opt,name=settings_id,json=settingsId,proto3" json:"settings_id,omitempty"`
	Batch      []*Batch `protobuf:"bytes,5,rep,name=batch" json:"batch,omitempty"`
	Sign       string   `protobuf:"bytes,6,opt,name=sign,proto3" json:"sign,omitempty"`
}

func (m *TransferRequest) Reset()                    { *m = TransferRequest{} }
func (m *TransferRequest) String() string            { return proto.CompactTextString(m) }
func (*TransferRequest) ProtoMessage()               {}
func (*TransferRequest) Descriptor() ([]byte, []int) { return fileDescriptorApi, []int{4} }

func (m *TransferRequest) GetCreatedAt() int64 {
	if m != nil {
		return m.CreatedAt
	}
	return 0
}

func (m *TransferRequest) GetSettingsId() int64 {
	if m != nil {
		return m.SettingsId
	}
	return 0
}

func (m *TransferRequest) GetBatch() []*Batch {
	if m != nil {
		return m.Batch
	}
	return nil
}

func (m *TransferRequest) GetSign() string {
	if m != nil {
		return m.Sign
	}
	return ""
}

type TransferResponse struct {
	State  *ActualState   `protobuf:"bytes,1,opt,name=state" json:"state,omitempty"`
	Result *TransferOK    `protobuf:"bytes,2,opt,name=result" json:"result,omitempty"`
	Error  *ErrorResponse `protobuf:"bytes,3,opt,name=error" json:"error,omitempty"`
}

func (m *TransferResponse) Reset()                    { *m = TransferResponse{} }
func (m *TransferResponse) String() string            { return proto.CompactTextString(m) }
func (*TransferResponse) ProtoMessage()               {}
func (*TransferResponse) Descriptor() ([]byte, []int) { return fileDescriptorApi, []int{5} }

func (m *TransferResponse) GetState() *ActualState {
	if m != nil {
		return m.State
	}
	return nil
}

func (m *TransferResponse) GetResult() *TransferOK {
	if m != nil {
		return m.Result
	}
	return nil
}

func (m *TransferResponse) GetError() *ErrorResponse {
	if m != nil {
		return m.Error
	}
	return nil
}

type Limit struct {
	Duration int64 `protobuf:"varint,1,opt,name=duration,proto3" json:"duration,omitempty"`
	Limit    int64 `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
}

func (m *Limit) Reset()                    { *m = Limit{} }
func (m *Limit) String() string            { return proto.CompactTextString(m) }
func (*Limit) ProtoMessage()               {}
func (*Limit) Descriptor() ([]byte, []int) { return fileDescriptorApi, []int{6} }

func (m *Limit) GetDuration() int64 {
	if m != nil {
		return m.Duration
	}
	return 0
}

func (m *Limit) GetLimit() int64 {
	if m != nil {
		return m.Limit
	}
	return 0
}

type Setting struct {
	Id       int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	PrevHash Hash     `protobuf:"bytes,2,opt,name=prev_hash,json=prevHash,proto3,customtype=Hash" json:"prev_hash"`
	Limits   []*Limit `protobuf:"bytes,3,rep,name=limits" json:"limits,omitempty"`
}

func (m *Setting) Reset()                    { *m = Setting{} }
func (m *Setting) String() string            { return proto.CompactTextString(m) }
func (*Setting) ProtoMessage()               {}
func (*Setting) Descriptor() ([]byte, []int) { return fileDescriptorApi, []int{7} }

func (m *Setting) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Setting) GetLimits() []*Limit {
	if m != nil {
		return m.Limits
	}
	return nil
}

type AccountSettingsRequest struct {
	Account Account `protobuf:"varint,1,opt,name=account,proto3,customtype=Account" json:"account"`
}

func (m *AccountSettingsRequest) Reset()                    { *m = AccountSettingsRequest{} }
func (m *AccountSettingsRequest) String() string            { return proto.CompactTextString(m) }
func (*AccountSettingsRequest) ProtoMessage()               {}
func (*AccountSettingsRequest) Descriptor() ([]byte, []int) { return fileDescriptorApi, []int{8} }

type AccountSettingsResponse struct {
	State    *ActualState `protobuf:"bytes,1,opt,name=state" json:"state,omitempty"`
	Settings []*Setting   `protobuf:"bytes,2,rep,name=settings" json:"settings,omitempty"`
}

func (m *AccountSettingsResponse) Reset()                    { *m = AccountSettingsResponse{} }
func (m *AccountSettingsResponse) String() string            { return proto.CompactTextString(m) }
func (*AccountSettingsResponse) ProtoMessage()               {}
func (*AccountSettingsResponse) Descriptor() ([]byte, []int) { return fileDescriptorApi, []int{9} }

func (m *AccountSettingsResponse) GetState() *ActualState {
	if m != nil {
		return m.State
	}
	return nil
}

func (m *AccountSettingsResponse) GetSettings() []*Setting {
	if m != nil {
		return m.Settings
	}
	return nil
}

type UpdateSettingsRequest struct {
	Account                 Account  `protobuf:"varint,1,opt,name=account,proto3,customtype=Account" json:"account"`
	PrevHash                Hash     `protobuf:"bytes,2,opt,name=prev_hash,json=prevHash,proto3,customtype=Hash" json:"prev_hash"`
	CreatedAt               int64    `protobuf:"varint,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Limits                  []*Limit `protobuf:"bytes,4,rep,name=limits" json:"limits,omitempty"`
	VerifyTransferSign      bool     `protobuf:"varint,5,opt,name=verify_transfer_sign,json=verifyTransferSign,proto3" json:"verify_transfer_sign,omitempty"`
	VerifySettingChangeSign bool     `protobuf:"varint,6,opt,name=verify_setting_change_sign,json=verifySettingChangeSign,proto3" json:"verify_setting_change_sign,omitempty"`
	PublicKey               string   `protobuf:"bytes,7,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	Sign                    string   `protobuf:"bytes,8,opt,name=sign,proto3" json:"sign,omitempty"`
}

func (m *UpdateSettingsRequest) Reset()                    { *m = UpdateSettingsRequest{} }
func (m *UpdateSettingsRequest) String() string            { return proto.CompactTextString(m) }
func (*UpdateSettingsRequest) ProtoMessage()               {}
func (*UpdateSettingsRequest) Descriptor() ([]byte, []int) { return fileDescriptorApi, []int{10} }

func (m *UpdateSettingsRequest) GetCreatedAt() int64 {
	if m != nil {
		return m.CreatedAt
	}
	return 0
}

func (m *UpdateSettingsRequest) GetLimits() []*Limit {
	if m != nil {
		return m.Limits
	}
	return nil
}

func (m *UpdateSettingsRequest) GetVerifyTransferSign() bool {
	if m != nil {
		return m.VerifyTransferSign
	}
	return false
}

func (m *UpdateSettingsRequest) GetVerifySettingChangeSign() bool {
	if m != nil {
		return m.VerifySettingChangeSign
	}
	return false
}

func (m *UpdateSettingsRequest) GetPublicKey() string {
	if m != nil {
		return m.PublicKey
	}
	return ""
}

func (m *UpdateSettingsRequest) GetSign() string {
	if m != nil {
		return m.Sign
	}
	return ""
}

type UpdateSettingsResponse struct {
	State  *ActualState      `protobuf:"bytes,1,opt,name=state" json:"state,omitempty"`
	Result *UpdateSettingsOK `protobuf:"bytes,2,opt,name=result" json:"result,omitempty"`
	Error  *ErrorResponse    `protobuf:"bytes,3,opt,name=error" json:"error,omitempty"`
}

func (m *UpdateSettingsResponse) Reset()                    { *m = UpdateSettingsResponse{} }
func (m *UpdateSettingsResponse) String() string            { return proto.CompactTextString(m) }
func (*UpdateSettingsResponse) ProtoMessage()               {}
func (*UpdateSettingsResponse) Descriptor() ([]byte, []int) { return fileDescriptorApi, []int{11} }

func (m *UpdateSettingsResponse) GetState() *ActualState {
	if m != nil {
		return m.State
	}
	return nil
}

func (m *UpdateSettingsResponse) GetResult() *UpdateSettingsOK {
	if m != nil {
		return m.Result
	}
	return nil
}

func (m *UpdateSettingsResponse) GetError() *ErrorResponse {
	if m != nil {
		return m.Error
	}
	return nil
}

type UpdateSettingsOK struct {
	LastSettingsId   int64 `protobuf:"varint,1,opt,name=last_settings_id,json=lastSettingsId,proto3" json:"last_settings_id,omitempty"`
	LastSettingsHash Hash  `protobuf:"bytes,2,opt,name=last_settings_hash,json=lastSettingsHash,proto3,customtype=Hash" json:"last_settings_hash"`
}

func (m *UpdateSettingsOK) Reset()                    { *m = UpdateSettingsOK{} }
func (m *UpdateSettingsOK) String() string            { return proto.CompactTextString(m) }
func (*UpdateSettingsOK) ProtoMessage()               {}
func (*UpdateSettingsOK) Descriptor() ([]byte, []int) { return fileDescriptorApi, []int{12} }

func (m *UpdateSettingsOK) GetLastSettingsId() int64 {
	if m != nil {
		return m.LastSettingsId
	}
	return 0
}

type PrevHashRequest struct {
	Account Account `protobuf:"varint,1,opt,name=account,proto3,customtype=Account" json:"account"`
}

func (m *PrevHashRequest) Reset()                    { *m = PrevHashRequest{} }
func (m *PrevHashRequest) String() string            { return proto.CompactTextString(m) }
func (*PrevHashRequest) ProtoMessage()               {}
func (*PrevHashRequest) Descriptor() ([]byte, []int) { return fileDescriptorApi, []int{13} }

type PrevHashResponse struct {
	State      *ActualState `protobuf:"bytes,1,opt,name=state" json:"state,omitempty"`
	SettingsId int64        `protobuf:"varint,2,opt,name=settings_id,json=settingsId,proto3" json:"settings_id,omitempty"`
}

func (m *PrevHashResponse) Reset()                    { *m = PrevHashResponse{} }
func (m *PrevHashResponse) String() string            { return proto.CompactTextString(m) }
func (*PrevHashResponse) ProtoMessage()               {}
func (*PrevHashResponse) Descriptor() ([]byte, []int) { return fileDescriptorApi, []int{14} }

func (m *PrevHashResponse) GetState() *ActualState {
	if m != nil {
		return m.State
	}
	return nil
}

func (m *PrevHashResponse) GetSettingsId() int64 {
	if m != nil {
		return m.SettingsId
	}
	return 0
}

type HistoryRequest struct {
	Account   Account                  `protobuf:"varint,1,opt,name=account,proto3,customtype=Account" json:"account"`
	Direction HistoryRequest_Direction `protobuf:"varint,2,opt,name=direction,proto3,enum=api_v1.HistoryRequest_Direction" json:"direction,omitempty"`
	PageSize  int32                    `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken string                   `protobuf:"bytes,3,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
}

func (m *HistoryRequest) Reset()                    { *m = HistoryRequest{} }
func (m *HistoryRequest) String() string            { return proto.CompactTextString(m) }
func (*HistoryRequest) ProtoMessage()               {}
func (*HistoryRequest) Descriptor() ([]byte, []int) { return fileDescriptorApi, []int{15} }

func (m *HistoryRequest) GetDirection() HistoryRequest_Direction {
	if m != nil {
		return m.Direction
	}
	return HistoryRequest_BOTH
}

func (m *HistoryRequest) GetPageSize() int32 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

func (m *HistoryRequest) GetPageToken() string {
	if m != nil {
		return m.PageToken
	}
	return ""
}

type HistoryResponse struct {
	State         *ActualState `protobuf:"bytes,1,opt,name=state" json:"state,omitempty"`
	Transactions  []*Txn       `protobuf:"bytes,2,rep,name=transactions" json:"transactions,omitempty"`
	NextPageToken string       `protobuf:"bytes,3,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
}

func (m *HistoryResponse) Reset()                    { *m = HistoryResponse{} }
func (m *HistoryResponse) String() string            { return proto.CompactTextString(m) }
func (*HistoryResponse) ProtoMessage()               {}
func (*HistoryResponse) Descriptor() ([]byte, []int) { return fileDescriptorApi, []int{16} }

func (m *HistoryResponse) GetState() *ActualState {
	if m != nil {
		return m.State
	}
	return nil
}

func (m *HistoryResponse) GetTransactions() []*Txn {
	if m != nil {
		return m.Transactions
	}
	return nil
}

func (m *HistoryResponse) GetNextPageToken() string {
	if m != nil {
		return m.NextPageToken
	}
	return ""
}

type Txn struct {
	Id             int64   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	BatchId        int64   `protobuf:"varint,2,opt,name=batch_id,json=batchId,proto3" json:"batch_id,omitempty"`
	Sender         int64   `protobuf:"varint,3,opt,name=sender,proto3" json:"sender,omitempty"`
	Receiver       int64   `protobuf:"varint,4,opt,name=receiver,proto3" json:"receiver,omitempty"`
	Amount         int64   `protobuf:"varint,5,opt,name=amount,proto3" json:"amount,omitempty"`
	Balance        int64   `protobuf:"varint,6,opt,name=balance,proto3" json:"balance,omitempty"`
	PrevHash       Hash    `protobuf:"bytes,7,opt,name=prev_hash,json=prevHash,proto3,customtype=Hash" json:"prev_hash"`
	LastReceiverId int64   `protobuf:"varint,8,opt,name=last_receiver_id,json=lastReceiverId,proto3" json:"last_receiver_id,omitempty"`
	InputsHash     Hash    `protobuf:"bytes,9,opt,name=inputs_hash,json=inputsHash,proto3,customtype=Hash" json:"inputs_hash"`
	ConfirmedBy    Account `protobuf:"varint,10,opt,name=confirmed_by,json=confirmedBy,proto3,customtype=Account" json:"confirmed_by"`
	CreatedAt      int64   `protobuf:"varint,11,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	ProcessedAt    int64   `protobuf:"varint,12,opt,name=processed_at,json=processedAt,proto3" json:"processed_at,omitempty"`
	Hash           Hash    `protobuf:"bytes,13,opt,name=hash,proto3,customtype=Hash" json:"hash"`
	SettingsId     int64   `protobuf:"varint,14,opt,name=settings_id,json=settingsId,proto3" json:"settings_id,omitempty"`
	Sign           string  `protobuf:"bytes,15,opt,name=sign,proto3" json:"sign,omitempty"`
}

func (m *Txn) Reset()                    { *m = Txn{} }
func (m *Txn) String() string            { return proto.CompactTextString(m) }
func (*Txn) ProtoMessage()               {}
func (*Txn) Descriptor() ([]byte, []int) { return fileDescriptorApi, []int{17} }

func (m *Txn) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Txn) GetBatchId() int64 {
	if m != nil {
		return m.BatchId
	}
	return 0
}

func (m *Txn) GetSender() int64 {
	if m != nil {
		return m.Sender
	}
	return 0
}

func (m *Txn) GetReceiver() int64 {
	if m != nil {
		return m.Receiver
	}
	return 0
}

func (m *Txn) GetAmount() int64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *Txn) GetBalance() int64 {
	if m != nil {
		return m.Balance
	}
	return 0
}

func (m *Txn) GetLastReceiverId() int64 {
	if m != nil {
		return m.LastReceiverId
	}
	return 0
}

func (m *Txn) GetCreatedAt() int64 {
	if m != nil {
		return m.CreatedAt
	}
	return 0
}

func (m *Txn) GetProcessedAt() int64 {
	if m != nil {
		return m.ProcessedAt
	}
	return 0
}

func (m *Txn) GetSettingsId() int64 {
	if m != nil {
		return m.SettingsId
	}
	return 0
}

func (m *Txn) GetSign() string {
	if m != nil {
		return m.Sign
	}
	return ""
}

type StatsRequest struct {
	Account Account `protobuf:"varint,1,opt,name=account,proto3,customtype=Account" json:"account"`
}

func (m *StatsRequest) Reset()                    { *m = StatsRequest{} }
func (m *StatsRequest) String() string            { return proto.CompactTextString(m) }
func (*StatsRequest) ProtoMessage()               {}
func (*StatsRequest) Descriptor() ([]byte, []int) { return fileDescriptorApi, []int{18} }

type StatsResponse struct {
	State          *ActualState `protobuf:"bytes,1,opt,name=state" json:"state,omitempty"`
	EmitterBalance int64        `protobuf:"varint,2,opt,name=emitter_balance,json=emitterBalance,proto3" json:"emitter_balance,omitempty"`
	Outputs        int64        `protobuf:"varint,3,opt,name=outputs,proto3" json:"outputs,omitempty"`
	Inputs         int64        `protobuf:"varint,4,opt,name=inputs,proto3" json:"inputs,omitempty"`
	Settings       int64        `protobuf:"varint,5,opt,name=settings,proto3" json:"settings,omitempty"`
}

func (m *StatsResponse) Reset()                    { *m = StatsResponse{} }
func (m *StatsResponse) String() string            { return proto.CompactTextString(m) }
func (*StatsResponse) ProtoMessage()               {}
func (*StatsResponse) Descriptor() ([]byte, []int) { return fileDescriptorApi, []int{19} }

func (m *StatsResponse) GetState() *ActualState {
	if m != nil {
		return m.State
	}
	return nil
}

func (m *StatsResponse) GetEmitterBalance() int64 {
	if m != nil {
		return m.EmitterBalance
	}
	return 0
}

func (m *StatsResponse) GetOutputs() int64 {
	if m != nil {
		return m.Outputs
	}
	return 0
}

func (m *StatsResponse) GetInputs() int64 {
	if m != nil {
		return m.Inputs
	}
	return 0
}

func (m *StatsResponse) GetSettings() int64 {
	if m != nil {
		return m.Settings
	}
	return 0
}

type AccountsRequest struct {
	Account Account `protobuf:"varint,1,opt,name=account,proto3,customtype=Account" json:"account"`
}

func (m *AccountsRequest) Reset()                    { *m = AccountsRequest{} }
func (m *AccountsRequest) String() string            { return proto.CompactTextString(m) }
func (*AccountsRequest) ProtoMessage()               {}
func (*AccountsRequest) Descriptor() ([]byte, []int) { return fileDescriptorApi, []int{20} }

type AccountsResponse struct {
	Accounts      []Account `protobuf:"varint,1,rep,packed,name=accounts,customtype=Account" json:"accounts,omitempty"`
	NextPageToken string    `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	TotalTimeNs   int64     `protobuf:"varint,3,opt,name=total_time_ns,json=totalTimeNs,proto3" json:"total_time_ns,omitempty"`
	TraceId       string    `protobuf:"bytes,4,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
}

func (m *AccountsResponse) Reset()                    { *m = AccountsResponse{} }
func (m *AccountsResponse) String() string            { return proto.CompactTextString(m) }
func (*AccountsResponse) ProtoMessage()               {}
func (*AccountsResponse) Descriptor() ([]byte, []int) { return fileDescriptorApi, []int{21} }

func (m *AccountsResponse) GetNextPageToken() string {
	if m != nil {
		return m.NextPageToken
	}
	return ""
}

func (m *AccountsResponse) GetTotalTimeNs() int64 {
	if m != nil {
		return m.TotalTimeNs
	}
	return 0
}

func (m *AccountsResponse) GetTraceId() string {
	if m != nil {
		return m.TraceId
	}
	return ""
}

func init() {
	proto.RegisterType((*ActualState)(nil), "api_v1.ActualState")
	proto.RegisterType((*ErrorResponse)(nil), "api_v1.ErrorResponse")
	proto.RegisterType((*TransferOK)(nil), "api_v1.TransferOK")
	proto.RegisterType((*Batch)(nil), "api_v1.Batch")
	proto.RegisterType((*TransferRequest)(nil), "api_v1.TransferRequest")
	proto.RegisterType((*TransferResponse)(nil), "api_v1.TransferResponse")
	proto.RegisterType((*Limit)(nil), "api_v1.Limit")
	proto.RegisterType((*Setting)(nil), "api_v1.Setting")
	proto.RegisterType((*AccountSettingsRequest)(nil), "api_v1.AccountSettingsRequest")
	proto.RegisterType((*AccountSettingsResponse)(nil), "api_v1.AccountSettingsResponse")
	proto.RegisterType((*UpdateSettingsRequest)(nil), "api_v1.UpdateSettingsRequest")
	proto.RegisterType((*UpdateSettingsResponse)(nil), "api_v1.UpdateSettingsResponse")
	proto.RegisterType((*UpdateSettingsOK)(nil), "api_v1.UpdateSettingsOK")
	proto.RegisterType((*PrevHashRequest)(nil), "api_v1.PrevHashRequest")
	proto.RegisterType((*PrevHashResponse)(nil), "api_v1.PrevHashResponse")
	proto.RegisterType((*HistoryRequest)(nil), "api_v1.HistoryRequest")
	proto.RegisterType((*HistoryResponse)(nil), "api_v1.HistoryResponse")
	proto.RegisterType((*Txn)(nil), "api_v1.Txn")
	proto.RegisterType((*StatsRequest)(nil), "api_v1.StatsRequest")
	proto.RegisterType((*StatsResponse)(nil), "api_v1.StatsResponse")
	proto.RegisterType((*AccountsRequest)(nil), "api_v1.AccountsRequest")
	proto.RegisterType((*AccountsResponse)(nil), "api_v1.AccountsResponse")
	proto.RegisterEnum("api_v1.ErrorResponse_ErrorType", ErrorResponse_ErrorType_name, ErrorResponse_ErrorType_value)
	proto.RegisterEnum("api_v1.HistoryRequest_Direction", HistoryRequest_Direction_name, HistoryRequest_Direction_value)
}

func init() { proto.RegisterFile("api.proto", fileDescriptorApi) }

var fileDescriptorApi = []byte{
	// 1369 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x57, 0xcd, 0x6e, 0xdb, 0xc6,
	0x13, 0x37, 0xf5, 0x49, 0x0e, 0x65, 0x49, 0xd8, 0x7f, 0x62, 0x33, 0xfa, 0x23, 0xb1, 0xcb, 0x22,
	0x8d, 0xd3, 0x34, 0x4e, 0xe2, 0x9e, 0xd2, 0x06, 0x09, 0x24, 0xd7, 0x70, 0x84, 0x18, 0xb6, 0x43,
	0x2b, 0x28, 0x7a, 0x29, 0x41, 0x51, 0x6b, 0x99, 0x88, 0x44, 0x32, 0xe4, 0xca, 0xb0, 0xf2, 0x1e,
	0x2d, 0x7a, 0xce, 0x1b, 0xf4, 0x09, 0x7a, 0xed, 0x0b, 0xf4, 0xd2, 0x83, 0x6f, 0x45, 0xdf, 0xa0,
	0xe7, 0x62, 0xbf, 0x48, 0x91, 0x92, 0x8d, 0x5a, 0xb7, 0xdd, 0x99, 0xd9, 0xe1, 0xcc, 0x6f, 0x7f,
	0x33, 0xb3, 0x04, 0xcd, 0x09, 0xbd, 0xed, 0x30, 0x0a, 0x48, 0x80, 0x2a, 0x4e, 0xe8, 0xd9, 0xe7,
	0xcf, 0x5a, 0x8f, 0x87, 0x1e, 0x39, 0x9b, 0xf4, 0xb7, 0xdd, 0x60, 0xfc, 0x64, 0x18, 0x0c, 0x83,
	0x27, 0x4c, 0xdd, 0x9f, 0x9c, 0xb2, 0x1d, 0xdb, 0xb0, 0x15, 0x3f, 0x66, 0xfe, 0xa6, 0x80, 0xde,
	0x76, 0xc9, 0xc4, 0x19, 0x9d, 0x10, 0x87, 0x60, 0xf4, 0x10, 0xaa, 0x8e, 0xeb, 0x06, 0x13, 0x9f,
	0x18, 0xca, 0xa6, 0xb2, 0x55, 0xec, 0x34, 0x7e, 0xbf, 0xdc, 0x58, 0xf9, 0xf3, 0x72, 0xa3, 0xda,
	0xe6, 0x62, 0x4b, 0xea, 0x91, 0x01, 0xd5, 0xbe, 0x33, 0x72, 0x7c, 0x17, 0x1b, 0x05, 0x6a, 0x6a,
	0xc9, 0x2d, 0x7a, 0x08, 0xda, 0xc8, 0x89, 0x89, 0x7d, 0xe6, 0xc4, 0x67, 0x46, 0x71, 0x53, 0xd9,
	0xd2, 0x3a, 0x35, 0xe1, 0xa6, 0xf4, 0xda, 0x89, 0xcf, 0x2c, 0x95, 0xaa, 0xe9, 0x0a, 0xdd, 0x87,
	0x06, 0x33, 0x0d, 0x42, 0x9b, 0x78, 0x63, 0x6c, 0xfb, 0xb1, 0x51, 0x62, 0xce, 0x6a, 0x54, 0x7c,
	0x14, 0xf6, 0xbc, 0x31, 0x3e, 0x8c, 0xd1, 0x1d, 0x50, 0x49, 0xe4, 0xb8, 0xd8, 0xf6, 0x06, 0x46,
	0x99, 0x3a, 0xb4, 0xaa, 0x6c, 0xdf, 0x1d, 0x98, 0xbf, 0x28, 0xb0, 0xba, 0x17, 0x45, 0x41, 0x64,
	0xe1, 0x38, 0x0c, 0xfc, 0x18, 0xa3, 0x5b, 0x50, 0xc6, 0x54, 0xc0, 0x32, 0xd0, 0x2c, 0xbe, 0x41,
	0x2f, 0x01, 0xd8, 0xc2, 0x26, 0xd3, 0x90, 0x47, 0x5c, 0xdf, 0xd9, 0xd8, 0xe6, 0xa8, 0x6d, 0x67,
	0x1c, 0xf0, 0x5d, 0x6f, 0x1a, 0x62, 0x4b, 0xc3, 0x72, 0x69, 0x3e, 0x03, 0x2d, 0x91, 0x23, 0x1d,
	0xaa, 0xfb, 0x7b, 0x87, 0x7b, 0x56, 0xfb, 0xa0, 0xb9, 0x42, 0x37, 0x9d, 0xf6, 0x41, 0xfb, 0x70,
	0x77, 0xaf, 0xa9, 0x20, 0x80, 0xca, 0xf1, 0xd1, 0x41, 0x77, 0xf7, 0x87, 0x66, 0xc1, 0x7c, 0x0b,
	0xd0, 0x8b, 0x1c, 0x3f, 0x3e, 0xc5, 0xd1, 0xd1, 0x1b, 0xb4, 0x01, 0x7a, 0x8c, 0x09, 0xf1, 0xfc,
	0x61, 0x4c, 0xd3, 0x60, 0xf0, 0x5a, 0x20, 0x45, 0xdd, 0x01, 0x32, 0x61, 0x95, 0x61, 0xd1, 0x77,
	0x88, 0x7b, 0x46, 0x4d, 0x38, 0xac, 0x3a, 0x15, 0x76, 0xa8, 0xac, 0x3b, 0x30, 0x0f, 0xa0, 0xcc,
	0x96, 0xe8, 0x11, 0xa8, 0x11, 0x76, 0xb1, 0x77, 0x8e, 0xa3, 0xab, 0x6e, 0x2a, 0x31, 0x40, 0x6b,
	0x50, 0x71, 0xc6, 0xec, 0x52, 0xb9, 0x4b, 0xb1, 0x33, 0x2f, 0x15, 0x68, 0xc8, 0x08, 0x2d, 0xfc,
	0x61, 0x82, 0x63, 0x82, 0x1e, 0x40, 0x25, 0xc6, 0xfe, 0xe0, 0x6a, 0xb7, 0x42, 0x8d, 0xee, 0x02,
	0xb8, 0x11, 0x76, 0x08, 0x1e, 0xd8, 0x8e, 0x74, 0xac, 0x09, 0x49, 0x9b, 0x50, 0x12, 0x84, 0x11,
	0x3e, 0xbf, 0x86, 0x04, 0x54, 0xcd, 0x48, 0x90, 0x43, 0xa6, 0x34, 0x87, 0xcc, 0xe7, 0x50, 0x66,
	0xa0, 0x18, 0xe5, 0xcd, 0xe2, 0x96, 0xbe, 0xb3, 0x2a, 0xaf, 0x8d, 0x41, 0x61, 0x71, 0x1d, 0x42,
	0x50, 0x8a, 0xbd, 0xa1, 0x6f, 0x54, 0xd8, 0xad, 0xb3, 0xb5, 0xf9, 0xb3, 0x02, 0xcd, 0x34, 0x41,
	0xc1, 0x8f, 0x87, 0x50, 0x8e, 0x29, 0xd9, 0x59, 0x82, 0xfa, 0xce, 0xff, 0xa4, 0xb7, 0x99, 0x3a,
	0xb0, 0xb8, 0x05, 0xfa, 0x12, 0x2a, 0x11, 0x8e, 0x27, 0x23, 0x9e, 0x9f, 0xbe, 0x83, 0xa4, 0x6d,
	0x7a, 0xaf, 0x96, 0xb0, 0x40, 0x8f, 0x24, 0xed, 0x8a, 0xcc, 0xf4, 0xf6, 0x42, 0x6e, 0x09, 0x36,
	0x9a, 0xcf, 0xa1, 0x7c, 0xe0, 0x8d, 0x3d, 0x82, 0x5a, 0xa0, 0x0e, 0x26, 0x91, 0x43, 0xbc, 0xc0,
	0x17, 0x94, 0x48, 0xf6, 0x94, 0xc8, 0x23, 0x6a, 0x24, 0xc0, 0xe5, 0x1b, 0xf3, 0x3d, 0x54, 0x4f,
	0x38, 0x34, 0xa8, 0x0e, 0x85, 0x84, 0x49, 0x05, 0x6f, 0x90, 0xc5, 0xbc, 0x70, 0x2d, 0xe6, 0xf7,
	0xa1, 0xc2, 0xdc, 0xc5, 0x46, 0x31, 0x8b, 0x29, 0x0b, 0xcb, 0x12, 0x4a, 0x73, 0x17, 0xd6, 0xc4,
	0xbd, 0x8b, 0x6f, 0xc6, 0x92, 0x27, 0xff, 0xbd, 0x53, 0x98, 0x1f, 0x60, 0x7d, 0xce, 0xc9, 0xcd,
	0xef, 0xe2, 0x11, 0xa8, 0x92, 0x12, 0x46, 0x81, 0xc5, 0xdc, 0x90, 0xd6, 0xc2, 0xad, 0x95, 0x18,
	0x98, 0x7f, 0x14, 0xe0, 0xf6, 0xbb, 0x70, 0xe0, 0x10, 0xbc, 0x7c, 0xdc, 0x37, 0x81, 0x33, 0x5b,
	0x0c, 0xc5, 0x7c, 0x31, 0xa4, 0x68, 0x97, 0xae, 0x41, 0x1b, 0x3d, 0x85, 0x5b, 0xe7, 0x38, 0xf2,
	0x4e, 0xa7, 0x36, 0x11, 0xfc, 0xb2, 0x19, 0xa5, 0x69, 0xcb, 0x53, 0x2d, 0xc4, 0x75, 0x92, 0x7a,
	0x27, 0xde, 0xd0, 0x47, 0xdf, 0x42, 0x4b, 0x9c, 0x10, 0xa9, 0xdb, 0xee, 0x99, 0xe3, 0x0f, 0xb1,
	0x9d, 0x94, 0x82, 0x6a, 0xad, 0x73, 0x0b, 0x01, 0xc4, 0x2e, 0xd3, 0xb3, 0xc3, 0x77, 0x01, 0xc2,
	0x49, 0x7f, 0xe4, 0xb9, 0xf6, 0x7b, 0x3c, 0x35, 0xaa, 0xac, 0x6e, 0x34, 0x2e, 0x79, 0x83, 0xa7,
	0x49, 0x41, 0xa9, 0x33, 0x05, 0xf5, 0x49, 0x81, 0xb5, 0x3c, 0xae, 0x37, 0xbf, 0xca, 0xa7, 0xb9,
	0xb2, 0x32, 0xa4, 0x6d, 0xd6, 0xf5, 0xb2, 0xc5, 0x75, 0x01, 0xcd, 0xbc, 0x23, 0xb4, 0x05, 0x4d,
	0xd6, 0x5c, 0xe7, 0x5b, 0x70, 0x9d, 0xca, 0x4f, 0xd2, 0x66, 0xf3, 0x0d, 0xa0, 0xac, 0xe5, 0x95,
	0xd7, 0xdf, 0x9c, 0x3d, 0x49, 0x25, 0xe6, 0x0b, 0x68, 0x1c, 0x0b, 0x4a, 0x2c, 0x51, 0x27, 0x3f,
	0x42, 0x33, 0x3d, 0x7d, 0x73, 0x54, 0x73, 0x6d, 0xb4, 0x90, 0x6f, 0xa3, 0xe6, 0x5f, 0x0a, 0xd4,
	0x5f, 0x7b, 0x31, 0x09, 0xa2, 0xe9, 0x12, 0xd5, 0xf0, 0x12, 0xb4, 0x81, 0x17, 0x61, 0x97, 0xb5,
	0x2a, 0x3e, 0x3f, 0x37, 0x65, 0x34, 0x59, 0xaf, 0xdb, 0xdf, 0x49, 0x3b, 0x2b, 0x3d, 0x82, 0xfe,
	0x0f, 0x5a, 0xe8, 0x30, 0x66, 0x7e, 0xc4, 0xac, 0xc7, 0x97, 0x2d, 0x95, 0x0a, 0x4e, 0xbc, 0x8f,
	0x98, 0x51, 0x91, 0x2a, 0x49, 0xf0, 0x1e, 0xfb, 0x7c, 0x5c, 0x58, 0xcc, 0xbc, 0x47, 0x05, 0xe6,
	0x57, 0xa0, 0x25, 0x3e, 0x91, 0x0a, 0xa5, 0xce, 0x51, 0xef, 0x75, 0x73, 0x85, 0x0e, 0xdb, 0xa3,
	0x77, 0xbd, 0xe3, 0x77, 0xbd, 0xa6, 0x82, 0x34, 0x28, 0x77, 0x0f, 0xe9, 0xb2, 0x60, 0xfe, 0xa4,
	0x40, 0x23, 0x89, 0xe8, 0xe6, 0x38, 0x3e, 0x81, 0x1a, 0x2b, 0x3f, 0x87, 0x7d, 0x4e, 0x36, 0x1b,
	0x3d, 0x69, 0xfd, 0x17, 0xbe, 0x95, 0x31, 0x40, 0x5f, 0x40, 0xc3, 0xc7, 0x17, 0xc4, 0x9e, 0xcb,
	0x60, 0x95, 0x8a, 0x8f, 0x93, 0x2c, 0xfe, 0x2e, 0x42, 0xb1, 0x77, 0xe1, 0xcf, 0xb5, 0xed, 0x3b,
	0xa0, 0xe6, 0x66, 0x7e, 0xb5, 0xcf, 0xe7, 0x3d, 0x9d, 0xdc, 0x62, 0x1a, 0xf3, 0x9e, 0x22, 0x87,
	0x6f, 0x6b, 0x66, 0xfc, 0xf3, 0x79, 0xb9, 0x68, 0xda, 0x97, 0x67, 0xa7, 0xfd, 0xec, 0x83, 0xad,
	0x32, 0xf7, 0x60, 0x4b, 0x1b, 0x5d, 0xf5, 0xda, 0x46, 0x27, 0xeb, 0x48, 0x7e, 0x8d, 0xc6, 0xac,
	0xa6, 0x75, 0x64, 0x09, 0x71, 0x77, 0x80, 0x1e, 0x83, 0xee, 0xf9, 0xe1, 0x84, 0x88, 0x02, 0xd2,
	0x16, 0xb8, 0x05, 0x6e, 0xc0, 0x1c, 0xef, 0x40, 0xcd, 0x0d, 0xfc, 0x53, 0x2f, 0x1a, 0xe3, 0x81,
	0xdd, 0x9f, 0x1a, 0xb0, 0x98, 0x8e, 0x7a, 0x62, 0xd4, 0x99, 0xe6, 0xba, 0xae, 0x9e, 0xef, 0xba,
	0x9f, 0x41, 0x2d, 0x8c, 0x02, 0x17, 0xc7, 0x31, 0x37, 0xa8, 0xf1, 0xf7, 0x54, 0x22, 0x6b, 0x13,
	0xb4, 0x09, 0x25, 0x16, 0xdd, 0xea, 0x82, 0xe8, 0x98, 0x26, 0x5f, 0x55, 0xf5, 0xb9, 0xc7, 0x89,
	0x6c, 0x93, 0x8d, 0x99, 0x36, 0xf9, 0x1c, 0x6a, 0x94, 0x52, 0xcb, 0x0c, 0xcb, 0x5f, 0x15, 0x58,
	0x15, 0x67, 0x6f, 0x4e, 0xdd, 0x07, 0xd0, 0xc0, 0x63, 0x8f, 0x10, 0x1c, 0xd9, 0xd9, 0xb7, 0x79,
	0x5d, 0x88, 0x3b, 0xe2, 0xc6, 0x0d, 0xa8, 0x06, 0x13, 0x42, 0xc1, 0x17, 0xc4, 0x92, 0x5b, 0xca,
	0x1e, 0x7e, 0x2b, 0x82, 0x57, 0x62, 0x47, 0x19, 0x97, 0x8c, 0x5f, 0xce, 0xab, 0x74, 0xda, 0xbe,
	0x80, 0x86, 0xc8, 0x63, 0x99, 0x8c, 0x3f, 0x29, 0xd0, 0x4c, 0x8f, 0x8b, 0xa4, 0x1f, 0x80, 0x2a,
	0xf4, 0xb1, 0xa1, 0x6c, 0x16, 0xb7, 0x8a, 0x1d, 0x3d, 0xf3, 0xb6, 0x95, 0xca, 0x45, 0xc5, 0x57,
	0x58, 0x50, 0x7c, 0xf4, 0x75, 0x4d, 0x02, 0xe2, 0x8c, 0x92, 0xff, 0x0c, 0x9e, 0xb7, 0xce, 0x84,
	0x0b, 0x7e, 0x33, 0x4a, 0x99, 0xdf, 0x8c, 0x9d, 0x7f, 0x8a, 0x50, 0x6c, 0x1f, 0x77, 0xd1, 0x2b,
	0x50, 0xe5, 0x00, 0x46, 0xeb, 0xf9, 0xd7, 0xa0, 0x48, 0xbe, 0x65, 0xcc, 0x2b, 0x78, 0x5a, 0xe6,
	0x0a, 0x7a, 0x0b, 0xf5, 0xec, 0x70, 0x42, 0x77, 0x17, 0x4f, 0x3f, 0xe9, 0xec, 0xde, 0x55, 0xea,
	0xc4, 0x65, 0x07, 0xf4, 0x7d, 0x4c, 0xe4, 0xe8, 0x48, 0xc3, 0xca, 0x8d, 0xa2, 0x34, 0xac, 0xfc,
	0x94, 0x31, 0x57, 0xd0, 0x2b, 0x80, 0x7d, 0x4c, 0x44, 0xd7, 0x44, 0x6b, 0x8b, 0x1b, 0x7b, 0x6b,
	0x7d, 0x4e, 0x9e, 0x38, 0x78, 0x0e, 0xea, 0x3e, 0x26, 0x8c, 0xb9, 0xe8, 0x56, 0xf2, 0x30, 0x9b,
	0x29, 0x82, 0xd6, 0xed, 0x9c, 0x34, 0x17, 0xbf, 0xa4, 0x40, 0x1a, 0x7f, 0x8e, 0x53, 0x69, 0xfc,
	0x79, 0xb6, 0x98, 0x2b, 0xe8, 0x7b, 0x40, 0xa9, 0x8f, 0x04, 0xda, 0x7b, 0xb9, 0x13, 0x79, 0x6c,
	0x37, 0xae, 0xd4, 0x4b, 0xc7, 0xfd, 0x0a, 0xfb, 0x51, 0xfe, 0xfa, 0xdf, 0x00, 0x00, 0x00, 0xff,
	0xff, 0x36, 0x2a, 0x9b, 0xc3, 0x6c, 0x0f, 0x00, 0x00,
}
